name: Build library and example bin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make and run example
      run: make example && ./example
